import AsyncStorage from '@react-native-community/async-storage';
import { Colors } from 'react-native-paper';

/**
 * Pref Key
 */
export const loggedStatus = 'loggedstatus';
export const initial = 'initial';
export const userID = 'userid';
export const userData = 'userData';
export const introDone = 'introDone';
export const saveToken = 'token';
export const USERTYPE = 'type';

//network
export const methodPost = 'POST';
export const methodGet = 'GET';

//erb Brand Color
export const RED = '#ea343c';
export const CARROT_ORANGE = '#f19e28';
export const GREY = '#5f5f5d';
export const HIPPIE_BLUE = '#47a5a5';
export const JET_BLACK = Colors.white; //'#3e3e40';
export const VIOLET_BLUE = '#af67a9';
export const WHITE_LINEN = '#ebe7de';
export const WHITE = 'white';

//colors
export const PRIMARY_COLOR = '#ea343c';
export const ACCENT_COLOR = '#f39f24';
export const BACKGROUND_COLOR = '#f4f5f8'; //'#f4f5f8';
export const GREY_COLOR = '#dedede';

export const cityList = [
  { value: 'abohar' },
  { value: 'Mumbai' },
  { value: 'Delhi' },
  { value: 'Bengaluru' },
  { value: 'Ahmedabad' },
  { value: 'Hyderabad' },
  { value: 'Chennai' },
  { value: 'Kolkata' },
  { value: 'Pune' },
  { value: 'Jaipur' },
  { value: 'Surat' },
  { value: 'Lucknow' },
  { value: 'Kanpur' },
  { value: 'Nagpur' },
  { value: 'Patna' },
  { value: 'Indore' },
  { value: 'Thane' },
  { value: 'Bhopal' },
  { value: 'Visakhapatnam' },
  { value: 'Vadodara' },
  { value: 'Firozabad' },
  { value: 'Ludhiana' },
  { value: 'Rajkot' },
  { value: 'Agra' },
  { value: 'Siliguri' },
  { value: 'Nashik' },
  { value: 'Faridabad' },
  { value: 'Patiala' },
  { value: 'Meerut' },
  { value: 'Kalyan-Dombivali' },
  { value: 'Vasai-Virar' },
  { value: 'Varanasi' },
  { value: 'Srinagar' },
  { value: 'Dhanbad' },
  { value: 'Jodhpur' },
  { value: 'Amritsar' },
  { value: 'Raipur' },
  { value: 'Allahabad' },
  { value: 'Coimbatore' },
  { value: 'Jabalpur' },
  { value: 'Gwalior' },
  { value: 'Vijayawada' },
  { value: 'Madurai' },
  { value: 'Guwahati' },
  { value: 'Chandigarh' },
  { value: 'Hubli-Dharwad' },
  { value: 'Amroha' },
  { value: 'Moradabad' },
  { value: 'Gurgaon' },
  { value: 'Aligarh' },
  { value: 'Solapur' },
  { value: 'Ranchi' },
  { value: 'Jalandhar' },
  { value: 'Tiruchirappalli' },
  { value: 'Bhubaneswar' },
  { value: 'Salem' },
  { value: 'Warangal' },
  { value: 'Mira-Bhayandar' },
  { value: 'Thiruvananthapuram' },
  { value: 'Bhiwandi' },
  { value: 'Saharanpur' },
  { value: 'Guntur' },
  { value: 'Amravati' },
  { value: 'Bikaner' },
  { value: 'Noida' },
  { value: 'Jamshedpur' },
  { value: 'Bhilai Nagar' },
  { value: 'Cuttack' },
  { value: 'Kochi' },
  { value: 'Udaipur' },
  { value: 'Bhavnagar' },
  { value: 'Dehradun' },
  { value: 'Asansol' },
  { value: 'Nanded-Waghala' },
  { value: 'Ajmer' },
  { value: 'Jamnagar' },
  { value: 'Ujjain' },
  { value: 'Sangli' },
  { value: 'Loni' },
  { value: 'Jhansi' },
  { value: 'Pondicherry' },
  { value: 'Nellore' },
  { value: 'Jammu' },
  { value: 'Belagavi' },
  { value: 'Raurkela' },
  { value: 'Mangaluru' },
  { value: 'Tirunelveli' },
  { value: 'Malegaon' },
  { value: 'Gaya' },
  { value: 'Tiruppur' },
  { value: 'Davanagere' },
  { value: 'Kozhikode' },
  { value: 'Akola' },
  { value: 'Kurnool' },
  { value: 'Bokaro Steel City' },
  { value: 'Rajahmundry' },
  { value: 'Ballari' },
  { value: 'Agartala' },
  { value: 'Bhagalpur' },
  { value: 'Latur' },
  { value: 'Dhule' },
  { value: 'Korba' },
  { value: 'Bhilwara' },
  { value: 'Brahmapur' },
  { value: 'Mysore' },
  { value: 'Muzaffarpur' },
  { value: 'Ahmednagar' },
  { value: 'Kollam' },
  { value: 'Raghunathganj' },
  { value: 'Bilaspur' },
  { value: 'Shahjahanpur' },
  { value: 'Thrissur' },
  { value: 'Alwar' },
  { value: 'Kakinada' },
  { value: 'Nizamabad' },
  { value: 'Sagar' },
  { value: 'Tumkur' },
  { value: 'Hisar' },
  { value: 'Rohtak' },
  { value: 'Panipat' },
  { value: 'Darbhanga' },
  { value: 'Kharagpur' },
  { value: 'Aizawl' },
  { value: 'Ichalkaranji' },
  { value: 'Tirupati' },
  { value: 'Karnal' },
  { value: 'Bathinda' },
  { value: 'Rampur' },
  { value: 'Shivamogga' },
  { value: 'Ratlam' },
  { value: 'Modinagar' },
  { value: 'Durg' },
  { value: 'Shillong' },
  { value: 'Imphal' },
  { value: 'Hapur' },
  { value: 'Ranipet' },
  { value: 'Anantapur' },
  { value: 'Arrah' },
  { value: 'Karimnagar' },
  { value: 'Parbhani' },
  { value: 'Etawah' },
  { value: 'Bharatpur' },
  { value: 'Begusarai' },
  { value: 'New Delhi' },
  { value: 'Chhapra' },
  { value: 'Kadapa' },
  { value: 'Ramagundam' },
  { value: 'Pali' },
  { value: 'Satna' },
  { value: 'Vizianagaram' },
  { value: 'Katihar' },
  { value: 'Hardwar' },
  { value: 'Sonipat' },
  { value: 'Nagercoil' },
  { value: 'Thanjavur' },
  { value: 'Murwara (Katni)' },
  { value: 'Naihati' },
  { value: 'Sambhal' },
  { value: 'Nadiad' },
  { value: 'Yamunanagar' },
  { value: 'English Bazar' },
  { value: 'Eluru' },
  { value: 'Munger' },
  { value: 'Panchkula' },
  { value: 'Raayachuru' },
  { value: 'Panvel' },
  { value: 'Deoghar' },
  { value: 'Ongole' },
  { value: 'Nandyal' },
  { value: 'Morena' },
  { value: 'Bhiwani' },
  { value: 'Porbandar' },
  { value: 'Palakkad' },
  { value: 'Anand' },
  { value: 'Purnia' },
  { value: 'Baharampur' },
  { value: 'Barmer' },
  { value: 'Morvi' },
  { value: 'Orai' },
  { value: 'Bahraich' },
  { value: 'Sikar' },
  { value: 'Vellore' },
  { value: 'Singrauli' },
  { value: 'Khammam' },
  { value: 'Mahesana' },
  { value: 'Silchar' },
  { value: 'Sambalpur' },
  { value: 'Rewa' },
  { value: 'Unnao' },
  { value: 'Hugli-Chinsurah' },
  { value: 'Raiganj' },
  { value: 'Phusro' },
  { value: 'Adityapur' },
  { value: 'Alappuzha' },
  { value: 'Bahadurgarh' },
  { value: 'Machilipatnam' },
  { value: 'Rae Bareli' },
  { value: 'Jalpaiguri' },
  { value: 'Bharuch' },
  { value: 'Pathankot' },
  { value: 'Hoshiarpur' },
  { value: 'Baramula' },
  { value: 'Adoni' },
  { value: 'Jind' },
  { value: 'Tonk' },
  { value: 'Tenali' },
  { value: 'Kancheepuram' },
  { value: 'Vapi' },
  { value: 'Sirsa' },
  { value: 'Navsari' },
  { value: 'Mahbubnagar' },
  { value: 'Puri' },
  { value: 'Robertson Pet' },
  { value: 'Erode' },
  { value: 'Batala' },
  { value: 'Haldwani-cum-Kathgodam' },
  { value: 'Vidisha' },
  { value: 'Saharsa' },
  { value: 'Thanesar' },
  { value: 'Chittoor' },
  { value: 'Veraval' },
  { value: 'Lakhimpur' },
  { value: 'Sitapur' },
  { value: 'Hindupur' },
  { value: 'Santipur' },
  { value: 'Balurghat' },
  { value: 'Ganjbasoda' },
  { value: 'Moga' },
  { value: 'Proddatur' },
  { value: 'Srinagar' },
  { value: 'Medinipur' },
  { value: 'Habra' },
  { value: 'Sasaram' },
  { value: 'Hajipur' },
  { value: 'Bhuj' },
  { value: 'Shivpuri' },
  { value: 'Ranaghat' },
  { value: 'Shimla' },
  { value: 'Tiruvannamalai' },
  { value: 'Kaithal' },
  { value: 'Rajnandgaon' },
  { value: 'Godhra' },
  { value: 'Hazaribag' },
  { value: 'Bhimavaram' },
  { value: 'Mandsaur' },
  { value: 'Dibrugarh' },
  { value: 'Kolar' },
  { value: 'Bankura' },
  { value: 'Mandya' },
  { value: 'Dehri-on-Sone' },
  { value: 'Madanapalle' },
  { value: 'Malerkotla' },
  { value: 'Lalitpur' },
  { value: 'Bettiah' },
  { value: 'Pollachi' },
  { value: 'Khanna' },
  { value: 'Neemuch' },
  { value: 'Palwal' },
  { value: 'Palanpur' },
  { value: 'Guntakal' },
  { value: 'Nabadwip' },
  { value: 'Udupi' },
  { value: 'Jagdalpur' },
  { value: 'Motihari' },
  { value: 'Pilibhit' },
  { value: 'Dimapur' },
  { value: 'Mohali' },
  { value: 'Sadulpur' },
  { value: 'Rajapalayam' },
  { value: 'Dharmavaram' },
  { value: 'Kashipur' },
  { value: 'Sivakasi' },
  { value: 'Darjiling' },
  { value: 'Chikkamagaluru' },
  { value: 'Gudivada' },
  { value: 'Baleshwar Town' },
  { value: 'Mancherial' },
  { value: 'Srikakulam' },
  { value: 'Adilabad' },
  { value: 'Yavatmal' },
  { value: 'Barnala' },
  { value: 'Nagaon' },
  { value: 'Narasaraopet' },
  { value: 'Raigarh' },
  { value: 'Roorkee' },
  { value: 'Valsad' },
  { value: 'Ambikapur' },
  { value: 'Giridih' },
  { value: 'Chandausi' },
  { value: 'Purulia' },
  { value: 'Patan' },
  { value: 'Bagaha' },
  { value: 'Hardoi ' },
  { value: 'Achalpur' },
  { value: 'Osmanabad' },
  { value: 'Deesa' },
  { value: 'Nandurbar' },
  { value: 'Azamgarh' },
  { value: 'Ramgarh' },
  { value: 'Firozpur' },
  { value: 'Baripada Town' },
  { value: 'Karwar' },
  { value: 'Siwan' },
  { value: 'Rajampet' },
  { value: 'Pudukkottai' },
  { value: 'Anantnag' },
  { value: 'Tadpatri' },
  { value: 'Satara' },
  { value: 'Bhadrak' },
  { value: 'Kishanganj' },
  { value: 'Suryapet' },
  { value: 'Wardha' },
  { value: 'Ranebennuru' },
  { value: 'Amreli' },
  { value: 'Neyveli (TS)' },
  { value: 'Jamalpur' },
  { value: 'Marmagao' },
  { value: 'Udgir' },
  { value: 'Tadepalligudem' },
  { value: 'Nagapattinam' },
  { value: 'Buxar' },
  { value: 'Aurangabad' },
  { value: 'Jehanabad' },
  { value: 'Phagwara' },
  { value: 'Khair' },
  { value: 'Sawai Madhopur' },
  { value: 'Kapurthala' },
  { value: 'Chilakaluripet' },
  { value: 'Aurangabad' },
  { value: 'Malappuram' },
  { value: 'Rewari' },
  { value: 'Nagaur' },
  { value: 'Sultanpur' },
  { value: 'Nagda' },
  { value: 'Port Blair' },
  { value: 'Lakhisarai' },
  { value: 'Panaji' },
  { value: 'Tinsukia' },
  { value: 'Itarsi' },
  { value: 'Kohima' },
  { value: 'Balangir' },
  { value: 'Nawada' },
  { value: 'Jharsuguda' },
  { value: 'Jagtial' },
  { value: 'Viluppuram' },
  { value: 'Amalner' },
  { value: 'Zirakpur' },
  { value: 'Tanda' },
  { value: 'Tiruchengode' },
  { value: 'Nagina' },
  { value: 'Yemmiganur' },
  { value: 'Vaniyambadi' },
  { value: 'Sarni' },
  { value: 'Theni Allinagaram' },
  { value: 'Margao' },
  { value: 'Akot' },
  { value: 'Sehore' },
  { value: 'Mhow Cantonment' },
  { value: 'Kot Kapura' },
  { value: 'Makrana' },
  { value: 'Pandharpur' },
  { value: 'Miryalaguda' },
  { value: 'Shamli' },
  { value: 'Seoni' },
  { value: 'Ranibennur' },
  { value: 'Kadiri' },
  { value: 'Shrirampur' },
  { value: 'Rudrapur' },
  { value: 'Parli' },
  { value: 'Najibabad' },
  { value: 'Nirmal' },
  { value: 'Udhagamandalam' },
  { value: 'Shikohabad' },
  { value: 'Jhumri Tilaiya' },
  { value: 'Aruppukkottai' },
  { value: 'Ponnani' },
  { value: 'Jamui' },
  { value: 'Sitamarhi' },
  { value: 'Chirala' },
  { value: 'Anjar' },
  { value: 'Karaikal' },
  { value: 'Hansi' },
  { value: 'Anakapalle' },
  { value: 'Mahasamund' },
  { value: 'Faridkot' },
  { value: 'Saunda' },
  { value: 'Dhoraji' },
  { value: 'Paramakudi' },
  { value: 'Balaghat' },
  { value: 'Sujangarh' },
  { value: 'Khambhat' },
  { value: 'Muktsar' },
  { value: 'Rajpura' },
  { value: 'Kavali' },
  { value: 'Dhamtari' },
  { value: 'Ashok Nagar' },
  { value: 'Sardarshahar' },
  { value: 'Mahuva' },
  { value: 'Bargarh' },
  { value: 'Kamareddy' },
  { value: 'Sahibganj' },
  { value: 'Kothagudem' },
  { value: 'Ramanagaram' },
  { value: 'Gokak' },
  { value: 'Tikamgarh' },
  { value: 'Araria' },
  { value: 'Rishikesh' },
  { value: 'Shahdol' },
  { value: 'Medininagar (Daltonganj)' },
  { value: 'Arakkonam' },
  { value: 'Washim' },
  { value: 'Sangrur' },
  { value: 'Bodhan' },
  { value: 'Fazilka' },
  { value: 'Palacole' },
  { value: 'Keshod' },
  { value: 'Sullurpeta' },
  { value: 'Wadhwan' },
  { value: 'Gurdaspur' },
  { value: 'Vatakara' },
  { value: 'Tura' },
  { value: 'Narnaul' },
  { value: 'Kharar' },
  { value: 'Yadgir' },
  { value: 'Ambejogai' },
  { value: 'Ankleshwar' },
  { value: 'Savarkundla' },
  { value: 'Paradip' },
  { value: 'Virudhachalam' },
  { value: 'Kanhangad' },
  { value: 'Kadi' },
  { value: 'Srivilliputhur' },
  { value: 'Gobindgarh' },
  { value: 'Tindivanam' },
  { value: 'Mansa' },
  { value: 'Taliparamba' },
  { value: 'Manmad' },
  { value: 'Tanuku' },
  { value: 'Rayachoti' },
  { value: 'Virudhunagar' },
  { value: 'Koyilandy' },
  { value: 'Jorhat' },
  { value: 'Karur' },
  { value: 'Valparai' },
  { value: 'Srikalahasti' },
  { value: 'Neyyattinkara' },
  { value: 'Bapatla' },
  { value: 'Fatehabad' },
  { value: 'Malout' },
  { value: 'Sankarankovil' },
  { value: 'Tenkasi' },
  { value: 'Ratnagiri' },
  { value: 'Rabkavi Banhatti' },
  { value: 'Sikandrabad' },
  { value: 'Chaibasa' },
  { value: 'Chirmiri' },
  { value: 'Palwancha' },
  { value: 'Bhawanipatna' },
  { value: 'Kayamkulam' },
  { value: 'Pithampur' },
  { value: 'Nabha' },
  { value: 'Shahabad, Hardoi' },
  { value: 'Dhenkanal' },
  { value: 'Uran Islampur' },
  { value: 'Gopalganj' },
  { value: 'Bongaigaon City' },
  { value: 'Palani' },
  { value: 'Pusad' },
  { value: 'Sopore' },
  { value: 'Pilkhuwa' },
  { value: 'Tarn Taran' },
  { value: 'Renukoot' },
  { value: 'Mandamarri' },
  { value: 'Shahabad' },
  { value: 'Barbil' },
  { value: 'Koratla' },
  { value: 'Madhubani' },
  { value: 'Arambagh' },
  { value: 'Gohana' },
  { value: 'Ladnu' },
  { value: 'Pattukkottai' },
  { value: 'Sirsi' },
  { value: 'Sircilla' },
  { value: 'Tamluk' },
  { value: 'Jagraon' },
  { value: 'AlipurdUrban Agglomerationr' },
  { value: 'Alirajpur' },
  { value: 'Tandur' },
  { value: 'Naidupet' },
  { value: 'Tirupathur' },
  { value: 'Tohana' },
  { value: 'Ratangarh' },
  { value: 'Dhubri' },
  { value: 'Masaurhi' },
  { value: 'Visnagar' },
  { value: 'Vrindavan' },
  { value: 'Nokha' },
  { value: 'Nagari' },
  { value: 'Narwana' },
  { value: 'Ramanathapuram' },
  { value: 'Ujhani' },
  { value: 'Samastipur' },
  { value: 'Laharpur' },
  { value: 'Sangamner' },
  { value: 'Nimbahera' },
  { value: 'Siddipet' },
  { value: 'Suri' },
  { value: 'Diphu' },
  { value: 'Jhargram' },
  { value: 'Shirpur-Warwade' },
  { value: 'Tilhar' },
  { value: 'Sindhnur' },
  { value: 'Udumalaipettai' },
  { value: 'Malkapur' },
  { value: 'Wanaparthy' },
  { value: 'Gudur' },
  { value: 'Kendujhar' },
  { value: 'Mandla' },
  { value: 'Mandi' },
  { value: 'Nedumangad' },
  { value: 'North Lakhimpur' },
  { value: 'Vinukonda' },
  { value: 'Tiptur' },
  { value: 'Gobichettipalayam' },
  { value: 'Sunabeda' },
  { value: 'Wani' },
  { value: 'Upleta' },
  { value: 'Narasapuram' },
  { value: 'Nuzvid' },
  { value: 'Tezpur' },
  { value: 'Una' },
  { value: 'Markapur' },
  { value: 'Sheopur' },
  { value: 'Thiruvarur' },
  { value: 'Sidhpur' },
  { value: 'Sahaswan' },
  { value: 'Suratgarh' },
  { value: 'Shajapur' },
  { value: 'Rayagada' },
  { value: 'Lonavla' },
  { value: 'Ponnur' },
  { value: 'Kagaznagar' },
  { value: 'Gadwal' },
  { value: 'Bhatapara' },
  { value: 'Kandukur' },
  { value: 'Sangareddy' },
  { value: 'Unjha' },
  { value: 'Lunglei' },
  { value: 'Karimganj' },
  { value: 'Kannur' },
  { value: 'Bobbili' },
  { value: 'Mokameh' },
  { value: 'Talegaon Dabhade' },
  { value: 'Anjangaon' },
  { value: 'Mangrol' },
  { value: 'Sunam' },
  { value: 'Gangarampur' },
  { value: 'Thiruvallur' },
  { value: 'Tirur' },
  { value: 'Rath' },
  { value: 'Jatani' },
  { value: 'Viramgam' },
  { value: 'Rajsamand' },
  { value: 'Yanam' },
  { value: 'Kottayam' },
  { value: 'Panruti' },
  { value: 'Dhuri' },
  { value: 'Namakkal' },
  { value: 'Kasaragod' },
  { value: 'Modasa' },
  { value: 'Rayadurg' },
  { value: 'Supaul' },
  { value: 'Kunnamkulam' },
  { value: 'Umred' },
  { value: 'Bellampalle' },
  { value: 'Sibsagar' },
  { value: 'Mandi Dabwali' },
  { value: 'Ottappalam' },
  { value: 'Dumraon' },
  { value: 'Samalkot' },
  { value: 'Jaggaiahpet' },
  { value: 'Goalpara' },
  { value: 'Tuni' },
  { value: 'Lachhmangarh' },
  { value: 'Bhongir' },
  { value: 'Amalapuram' },
  { value: 'Firozpur Cantt.' },
  { value: 'Vikarabad' },
  { value: 'Thiruvalla' },
  { value: 'Sherkot' },
  { value: 'Palghar' },
  { value: 'Shegaon' },
  { value: 'Jangaon' },
  { value: 'Bheemunipatnam' },
  { value: 'Panna' },
  { value: 'Thodupuzha' },
  { value: 'KathUrban Agglomeration' },
  { value: 'Palitana' },
  { value: 'Arwal' },
  { value: 'Venkatagiri' },
  { value: 'Kalpi' },
  { value: 'Rajgarh (Churu)' },
  { value: 'Sattenapalle' },
  { value: 'Arsikere' },
  { value: 'Ozar' },
  { value: 'Thirumangalam' },
  { value: 'Petlad' },
  { value: 'Nasirabad' },
  { value: 'Phaltan' },
  { value: 'Rampurhat' },
  { value: 'Nanjangud' },
  { value: 'Forbesganj' },
  { value: 'Tundla' },
  { value: 'BhabUrban Agglomeration' },
  { value: 'Sagara' },
  { value: 'Pithapuram' },
  { value: 'Sira' },
  { value: 'Bhadrachalam' },
  { value: 'Charkhi Dadri' },
  { value: 'Chatra' },
  { value: 'Palasa Kasibugga' },
  { value: 'Nohar' },
  { value: 'Yevla' },
  { value: 'Sirhind Fatehgarh Sahib' },
  { value: 'Bhainsa' },
  { value: 'Parvathipuram' },
  { value: 'Shahade' },
  { value: 'Chalakudy' },
  { value: 'Narkatiaganj' },
  { value: 'Kapadvanj' },
  { value: 'Macherla' },
  { value: 'Raghogarh-Vijaypur' },
  { value: 'Rupnagar' },
  { value: 'Naugachhia' },
  { value: 'Sendhwa' },
  { value: 'Byasanagar' },
  { value: 'Sandila' },
  { value: 'Gooty' },
  { value: 'Salur' },
  { value: 'Nanpara' },
  { value: 'Sardhana' },
  { value: 'Vita' },
  { value: 'Gumia' },
  { value: 'Puttur' },
  { value: 'Jalandhar Cantt.' },
  { value: 'Nehtaur' },
  { value: 'Changanassery' },
  { value: 'Mandapeta' },
  { value: 'Dumka' },
  { value: 'Seohara' },
  { value: 'Umarkhed' },
  { value: 'Madhupur' },
  { value: 'Vikramasingapuram' },
  { value: 'Punalur' },
  { value: 'Kendrapara' },
  { value: 'Sihor' },
  { value: 'Nellikuppam' },
  { value: 'Samana' },
  { value: 'Warora' },
  { value: 'Nilambur' },
  { value: 'Rasipuram' },
  { value: 'Ramnagar' },
  { value: 'Jammalamadugu' },
  { value: 'Nawanshahr' },
  { value: 'Thoubal' },
  { value: 'Athni' },
  { value: 'Cherthala' },
  { value: 'Sidhi' },
  { value: 'Farooqnagar' },
  { value: 'Peddapuram' },
  { value: 'Chirkunda' },
  { value: 'Pachora' },
  { value: 'Madhepura' },
  { value: 'Pithoragarh' },
  { value: 'Tumsar' },
  { value: 'Phalodi' },
  { value: 'Tiruttani' },
  { value: 'Rampura Phul' },
  { value: 'Perinthalmanna' },
  { value: 'Padrauna' },
  { value: 'Pipariya' },
  { value: 'Dalli-Rajhara' },
  { value: 'Punganur' },
  { value: 'Mattannur' },
  { value: 'Mathura' },
  { value: 'Thakurdwara' },
  { value: 'Nandivaram-Guduvancheri' },
  { value: 'Mulbagal' },
  { value: 'Manjlegaon' },
  { value: 'Wankaner' },
  { value: 'Sillod' },
  { value: 'Nidadavole' },
  { value: 'Surapura' },
  { value: 'Rajagangapur' },
  { value: 'Sheikhpura' },
  { value: 'Parlakhemundi' },
  { value: 'Kalimpong' },
  { value: 'Siruguppa' },
  { value: 'Arvi' },
  { value: 'Limbdi' },
  { value: 'Barpeta' },
  { value: 'Manglaur' },
  { value: 'Repalle' },
  { value: 'Mudhol' },
  { value: 'Shujalpur' },
  { value: 'Mandvi' },
  { value: 'Thangadh' },
  { value: 'Sironj' },
  { value: 'Nandura' },
  { value: 'Shoranur' },
  { value: 'Nathdwara' },
  { value: 'Periyakulam' },
  { value: 'Sultanganj' },
  { value: 'Medak' },
  { value: 'Narayanpet' },
  { value: 'Raxaul Bazar' },
  { value: 'Rajauri' },
  { value: 'Pernampattu' },
  { value: 'Nainital' },
  { value: 'Ramachandrapuram' },
  { value: 'Vaijapur' },
  { value: 'Nangal' },
  { value: 'Sidlaghatta' },
  { value: 'Punch' },
  { value: 'Pandhurna' },
  { value: 'Wadgaon Road' },
  { value: 'Talcher' },
  { value: 'Varkala' },
  { value: 'Pilani' },
  { value: 'Nowgong' },
  { value: 'Naila Janjgir' },
  { value: 'Mapusa' },
  { value: 'Vellakoil' },
  { value: 'Merta City' },
  { value: 'Sivaganga' },
  { value: 'Mandideep' },
  { value: 'Sailu' },
  { value: 'Vyara' },
  { value: 'Kovvur' },
  { value: 'Vadalur' },
  { value: 'Nawabganj' },
  { value: 'Padra' },
  { value: 'Sainthia' },
  { value: 'Siana' },
  { value: 'Shahpur' },
  { value: 'Sojat' },
  { value: 'Noorpur' },
  { value: 'Paravoor' },
  { value: 'Murtijapur' },
  { value: 'Ramnagar' },
  { value: 'Sundargarh' },
  { value: 'Taki' },
  { value: 'Saundatti-Yellamma' },
  { value: 'Pathanamthitta' },
  { value: 'Wadi' },
  { value: 'Rameshwaram' },
  { value: 'Tasgaon' },
  { value: 'Sikandra Rao' },
  { value: 'Sihora' },
  { value: 'Tiruvethipuram' },
  { value: 'Tiruvuru' },
  { value: 'Mehkar' },
  { value: 'Peringathur' },
  { value: 'Perambalur' },
  { value: 'Manvi' },
  { value: 'Zunheboto' },
  { value: 'Mahnar Bazar' },
  { value: 'Attingal' },
  { value: 'Shahbad' },
  { value: 'Puranpur' },
  { value: 'Nelamangala' },
  { value: 'Nakodar' },
  { value: 'Lunawada' },
  { value: 'Murshidabad' },
  { value: 'Mahe' },
  { value: 'Lanka' },
  { value: 'Rudauli' },
  { value: 'Tuensang' },
  { value: 'Lakshmeshwar' },
  { value: 'Zira' },
  { value: 'Yawal' },
  { value: 'Thana Bhawan' },
  { value: 'Ramdurg' },
  { value: 'Pulgaon' },
  { value: 'Sadasivpet' },
  { value: 'Nargund' },
  { value: 'Neem-Ka-Thana' },
  { value: 'Memari' },
  { value: 'Nilanga' },
  { value: 'Naharlagun' },
  { value: 'Pakaur' },
  { value: 'Wai' },
  { value: 'Tarikere' },
  { value: 'Malavalli' },
  { value: 'Raisen' },
  { value: 'Lahar' },
  { value: 'Uravakonda' },
  { value: 'Savanur' },
  { value: 'Sirohi' },
  { value: 'Udhampur' },
  { value: 'Umarga' },
  { value: 'Pratapgarh' },
  { value: 'Lingsugur' },
  { value: 'Usilampatti' },
  { value: 'Palia Kalan' },
  { value: 'Wokha' },
  { value: 'Rajpipla' },
  { value: 'Vijayapura' },
  { value: 'Rawatbhata' },
  { value: 'Sangaria' },
  { value: 'Paithan' },
  { value: 'Rahuri' },
  { value: 'Patti' },
  { value: 'Zaidpur' },
  { value: 'Lalsot' },
  { value: 'Maihar' },
  { value: 'Vedaranyam' },
  { value: 'Nawapur' },
  { value: 'Solan' },
  { value: 'Vapi' },
  { value: 'Sanawad' },
  { value: 'Warisaliganj' },
  { value: 'Revelganj' },
  { value: 'Sabalgarh' },
  { value: 'Tuljapur' },
  { value: 'Simdega' },
  { value: 'Musabani' },
  { value: 'Kodungallur' },
  { value: 'Phulabani' },
  { value: 'Umreth' },
  { value: 'Narsipatnam' },
  { value: 'Nautanwa' },
  { value: 'Rajgir' },
  { value: 'Yellandu' },
  { value: 'Sathyamangalam' },
  { value: 'Pilibanga' },
  { value: 'Morshi' },
  { value: 'Pehowa' },
  { value: 'Sonepur' },
  { value: 'Pappinisseri' },
  { value: 'Zamania' },
  { value: 'Mihijam' },
  { value: 'Purna' },
  { value: 'Puliyankudi' },
  { value: 'Shikarpur, Bulandshahr' },
  { value: 'Umaria' },
  { value: 'Porsa' },
  { value: 'Naugawan Sadat' },
  { value: 'Fatehpur Sikri' },
  { value: 'Manuguru' },
  { value: 'Udaipur' },
  { value: 'Pipar City' },
  { value: 'Pattamundai' },
  { value: 'Nanjikottai' },
  { value: 'Taranagar' },
  { value: 'Yerraguntla' },
  { value: 'Satana' },
  { value: 'Sherghati' },
  { value: 'Sankeshwara' },
  { value: 'Madikeri' },
  { value: 'Thuraiyur' },
  { value: 'Sanand' },
  { value: 'Rajula' },
  { value: 'Kyathampalle' },
  { value: 'Shahabad, Rampur' },
  { value: 'Tilda Newra' },
  { value: 'Narsinghgarh' },
  { value: 'Chittur-Thathamangalam' },
  { value: 'Malaj Khand' },
  { value: 'Sarangpur' },
  { value: 'Robertsganj' },
  { value: 'Sirkali' },
  { value: 'Radhanpur' },
  { value: 'Tiruchendur' },
  { value: 'Utraula' },
  { value: 'Patratu' },
  { value: 'Vijainagar, Ajmer' },
  { value: 'Periyasemur' },
  { value: 'Pathri' },
  { value: 'Sadabad' },
  { value: 'Talikota' },
  { value: 'Sinnar' },
  { value: 'Mungeli' },
  { value: 'Sedam' },
  { value: 'Shikaripur' },
  { value: 'Sumerpur' },
  { value: 'Sattur' },
  { value: 'Sugauli' },
  { value: 'Lumding' },
  { value: 'Vandavasi' },
  { value: 'Titlagarh' },
  { value: 'Uchgaon' },
  { value: 'Mokokchung' },
  { value: 'Paschim Punropara' },
  { value: 'Sagwara' },
  { value: 'Ramganj Mandi' },
  { value: 'Tarakeswar' },
  { value: 'Mahalingapura' },
  { value: 'Dharmanagar' },
  { value: 'Mahemdabad' },
  { value: 'Manendragarh' },
  { value: 'Uran' },
  { value: 'Tharamangalam' },
  { value: 'Tirukkoyilur' },
  { value: 'Pen' },
  { value: 'Makhdumpur' },
  { value: 'Maner' },
  { value: 'Oddanchatram' },
  { value: 'Palladam' },
  { value: 'Mundi' },
  { value: 'Nabarangapur' },
  { value: 'Mudalagi' },
  { value: 'Samalkha' },
  { value: 'Nepanagar' },
  { value: 'Karjat' },
  { value: 'Ranavav' },
  { value: 'Pedana' },
  { value: 'Pinjore' },
  { value: 'Lakheri' },
  { value: 'Pasan' },
  { value: 'Puttur' },
  { value: 'Vadakkuvalliyur' },
  { value: 'Tirukalukundram' },
  { value: 'Mahidpur' },
  { value: 'Mussoorie' },
  { value: 'Muvattupuzha' },
  { value: 'Rasra' },
  { value: 'Udaipurwati' },
  { value: 'Manwath' },
  { value: 'Adoor' },
  { value: 'Uthamapalayam' },
  { value: 'Partur' },
  { value: 'Nahan' },
  { value: 'Ladwa' },
  { value: 'Mankachar' },
  { value: 'Nongstoin' },
  { value: 'Losal' },
  { value: 'Sri Madhopur' },
  { value: 'Ramngarh' },
  { value: 'Mavelikkara' },
  { value: 'Rawatsar' },
  { value: 'Rajakhera' },
  { value: 'Lar' },
  { value: 'Lal Gopalganj Nindaura' },
  { value: 'Muddebihal' },
  { value: 'Sirsaganj' },
  { value: 'Shahpura' },
  { value: 'Surandai' },
  { value: 'Sangole' },
  { value: 'Pavagada' },
  { value: 'Tharad' },
  { value: 'Mansa' },
  { value: 'Umbergaon' },
  { value: 'Mavoor' },
  { value: 'Nalbari' },
  { value: 'Talaja' },
  { value: 'Malur' },
  { value: 'Mangrulpir' },
  { value: 'Soro' },
  { value: 'Shahpura' },
  { value: 'Vadnagar' },
  { value: 'Raisinghnagar' },
  { value: 'Sindhagi' },
  { value: 'Sanduru' },
  { value: 'Sohna' },
  { value: 'Manavadar' },
  { value: 'Pihani' },
  { value: 'Safidon' },
  { value: 'Risod' },
  { value: 'Rosera' },
  { value: 'Sankari' },
  { value: 'Malpura' },
  { value: 'Sonamukhi' },
  { value: 'Shamsabad, Agra' },
  { value: 'Nokha' },
  { value: 'PandUrban Agglomeration' },
  { value: 'Mainaguri' },
  { value: 'Afzalpur' },
  { value: 'Shirur' },
  { value: 'Salaya' },
  { value: 'Shenkottai' },
  { value: 'Pratapgarh' },
  { value: 'Vadipatti' },
  { value: 'Nagarkurnool' },
  { value: 'Savner' },
  { value: 'Sasvad' },
  { value: 'Rudrapur' },
  { value: 'Soron' },
  { value: 'Sholingur' },
  { value: 'Pandharkaoda' },
  { value: 'Perumbavoor' },
  { value: 'Maddur' },
  { value: 'Nadbai' },
  { value: 'Talode' },
  { value: 'Shrigonda' },
  { value: 'Madhugiri' },
  { value: 'Tekkalakote' },
  { value: 'Seoni-Malwa' },
  { value: 'Shirdi' },
  { value: 'SUrban Agglomerationr' },
  { value: 'Terdal' },
  { value: 'Raver' },
  { value: 'Tirupathur' },
  { value: 'Taraori' },
  { value: 'Mukhed' },
  { value: 'Manachanallur' },
  { value: 'Rehli' },
  { value: 'Sanchore' },
  { value: 'Rajura' },
  { value: 'Piro' },
  { value: 'Mudabidri' },
  { value: 'Vadgaon Kasba' },
  { value: 'Nagar' },
  { value: 'Vijapur' },
  { value: 'Viswanatham' },
  { value: 'Polur' },
  { value: 'Panagudi' },
  { value: 'Manawar' },
  { value: 'Tehri' },
  { value: 'Samdhan' },
  { value: 'Pardi' },
  { value: 'Rahatgarh' },
  { value: 'Panagar' },
  { value: 'Uthiramerur' },
  { value: 'Tirora' },
  { value: 'Rangia' },
  { value: 'Sahjanwa' },
  { value: 'Wara Seoni' },
  { value: 'Magadi' },
  { value: 'Rajgarh (Alwar)' },
  { value: 'Rafiganj' },
  { value: 'Tarana' },
  { value: 'Rampur Maniharan' },
  { value: 'Sheoganj' },
  { value: 'Raikot' },
  { value: 'Pauri' },
  { value: 'Sumerpur' },
  { value: 'Navalgund' },
  { value: 'Shahganj' },
  { value: 'Marhaura' },
  { value: 'Tulsipur' },
  { value: 'Sadri' },
  { value: 'Thiruthuraipoondi' },
  { value: 'Shiggaon' },
  { value: 'Pallapatti' },
  { value: 'Mahendragarh' },
  { value: 'Sausar' },
  { value: 'Ponneri' },
  { value: 'Mahad' },
  { value: 'Lohardaga' },
  { value: 'Tirwaganj' },
  { value: 'Margherita' },
  { value: 'Sundarnagar' },
  { value: 'Rajgarh' },
  { value: 'Mangaldoi' },
  { value: 'Renigunta' },
  { value: 'Longowal' },
  { value: 'Ratia' },
  { value: 'Lalgudi' },
  { value: 'Shrirangapattana' },
  { value: 'Niwari' },
  { value: 'Natham' },
  { value: 'Unnamalaikadai' },
  { value: 'PurqUrban Agglomerationzi' },
  { value: 'Shamsabad, Farrukhabad' },
  { value: 'Mirganj' },
  { value: 'Todaraisingh' },
  { value: 'Warhapur' },
  { value: 'Rajam' },
  { value: 'Urmar Tanda' },
  { value: 'Lonar' },
  { value: 'Powayan' },
  { value: 'P.N.Patti' },
  { value: 'Palampur' },
  { value: 'Srisailam Project (Right Flank Colony) Township' },
  { value: 'Sindagi' },
  { value: 'Sandi' },
  { value: 'Vaikom' },
  { value: 'Malda' },
  { value: 'Tharangambadi' },
  { value: 'Sakaleshapura' },
  { value: 'Lalganj' },
  { value: 'Malkangiri' },
  { value: 'Rapar' },
  { value: 'Mauganj' },
  { value: 'Todabhim' },
  { value: 'Srinivaspur' },
  { value: 'Murliganj' },
  { value: 'Reengus' },
  { value: 'Sawantwadi' },
  { value: 'Tittakudi' },
  { value: 'Lilong' },
  { value: 'Rajaldesar' },
  { value: 'Pathardi' },
  { value: 'Achhnera' },
  { value: 'Pacode' },
  { value: 'Naraura' },
  { value: 'Nakur' },
  { value: 'Palai' },
  { value: 'Morinda, India' },
  { value: 'Manasa' },
  { value: 'Nainpur' },
  { value: 'Sahaspur' },
  { value: 'Pauni' },
  { value: 'Prithvipur' },
  { value: 'Ramtek' },
  { value: 'Silapathar' },
  { value: 'Songadh' },
  { value: 'Safipur' },
  { value: 'Sohagpur' },
  { value: 'Mul' },
  { value: 'Sadulshahar' },
  { value: 'Phillaur' },
  { value: 'Sambhar' },
  { value: 'Prantij' },
  { value: 'Nagla' },
  { value: 'Pattran' },
  { value: 'Mount Abu' },
  { value: 'Reoti' },
  { value: 'Tenu dam-cum-Kathhara' },
  { value: 'Panchla' },
  { value: 'Sitarganj' },
  { value: 'Pasighat' },
  { value: 'Motipur' },
  { value: "O' Valley" },
  { value: 'Raghunathpur' },
  { value: 'Suriyampalayam' },
  { value: 'Qadian' },
  { value: 'Rairangpur' },
  { value: 'Silvassa' },
  { value: 'Nowrozabad (Khodargama)' },
  { value: 'Mangrol' },
  { value: 'Soyagaon' },
  { value: 'Sujanpur' },
  { value: 'Manihari' },
  { value: 'Sikanderpur' },
  { value: 'Mangalvedhe' },
  { value: 'Phulera' },
  { value: 'Ron' },
  { value: 'Sholavandan' },
  { value: 'Saidpur' },
  { value: 'Shamgarh' },
  { value: 'Thammampatti' },
  { value: 'Maharajpur' },
  { value: 'Multai' },
  { value: 'Mukerian' },
  { value: 'Sirsi' },
  { value: 'Purwa' },
  { value: 'Sheohar' },
  { value: 'Namagiripettai' },
  { value: 'Parasi' },
  { value: 'Lathi' },
  { value: 'Lalganj' },
  { value: 'Narkhed' },
  { value: 'Mathabhanga' },
  { value: 'Shendurjana' },
  { value: 'Peravurani' },
  { value: 'Mariani' },
  { value: 'Phulpur' },
  { value: 'Rania' },
  { value: 'Pali' },
  { value: 'Pachore' },
  { value: 'Parangipettai' },
  { value: 'Pudupattinam' },
  { value: 'Panniyannur' },
  { value: 'Maharajganj' },
  { value: 'Rau' },
  { value: 'Monoharpur' },
  { value: 'Mandawa' },
  { value: 'Marigaon' },
  { value: 'Pallikonda' },
  { value: 'Pindwara' },
  { value: 'Shishgarh' },
  { value: 'Patur' },
  { value: 'Mayang Imphal' },
  { value: 'Mhowgaon' },
  { value: 'Guruvayoor' },
  { value: 'Mhaswad' },
  { value: 'Sahawar' },
  { value: 'Sivagiri' },
  { value: 'Mundargi' },
  { value: 'Punjaipugalur' },
  { value: 'Kailasahar' },
  { value: 'Samthar' },
  { value: 'Sakti' },
  { value: 'Sadalagi' },
  { value: 'Silao' },
  { value: 'Mandalgarh' },
  { value: 'Loha' },
  { value: 'Pukhrayan' },
  { value: 'Padmanabhapuram' },
  { value: 'Belonia' },
  { value: 'Saiha' },
  { value: 'Srirampore' },
  { value: 'Talwara' },
  { value: 'Puthuppally' },
  { value: 'Khowai' },
  { value: 'Vijaypur' },
  { value: 'Takhatgarh' },
  { value: 'Thirupuvanam' },
  { value: 'Adra' },
  { value: 'Piriyapatna' },
  { value: 'Obra' },
  { value: 'Adalaj' },
  { value: 'Nandgaon' },
  { value: 'Barh' },
  { value: 'Chhapra' },
  { value: 'Panamattom' },
  { value: 'Niwai' },
  { value: 'Bageshwar' },
  { value: 'Tarbha' },
  { value: 'Adyar' },
  { value: 'Narsinghgarh' },
  { value: 'Warud' },
  { value: 'Asarganj' },
  { value: 'Sarsod' },
];

export const citiesList = [
  { value: 'Mumbai' },
  { value: 'Delhi' },
  { value: 'Bengaluru' },
  { value: 'Ahmedabad' },
  { value: 'Hyderabad' },
  { value: 'Chennai' },
  { value: 'Kolkata' },
  { value: 'Pune' },
  { value: 'Jaipur' },
  { value: 'Surat' },
  { value: 'Lucknow' },
  { value: 'Kanpur' },
  { value: 'Nagpur' },
  { value: 'Patna' },
  { value: 'Indore' },
  { value: 'Thane' },
  { value: 'Bhopal' },
  { value: 'Visakhapatnam' },
  { value: 'Vadodara' },
  { value: 'Firozabad' },
  { value: 'Ludhiana' },
  { value: 'Rajkot' },
  { value: 'Agra' },
  { value: 'Siliguri' },
  { value: 'Nashik' },
  { value: 'Faridabad' },
  { value: 'Patiala' },
  { value: 'Meerut' },
  { value: 'Kalyan-Dombivali' },
  { value: 'Vasai-Virar' },
  { value: 'Varanasi' },
  { value: 'Srinagar' },
  { value: 'Dhanbad' },
  { value: 'Jodhpur' },
  { value: 'Amritsar' },
  { value: 'Raipur' },
  { value: 'Allahabad' },
  { value: 'Coimbatore' },
  { value: 'Jabalpur' },
  { value: 'Gwalior' },
  { value: 'Vijayawada' },
  { value: 'Madurai' },
  { value: 'Guwahati' },
  { value: 'Chandigarh' },
  { value: 'Hubli-Dharwad' },
  { value: 'Amroha' },
  { value: 'Moradabad' },
  { value: 'Gurgaon' },
  { value: 'Aligarh' },
  { value: 'Solapur' },
  { value: 'Ranchi' },
  { value: 'Jalandhar' },
  { value: 'Tiruchirappalli' },
  { value: 'Bhubaneswar' },
  { value: 'Salem' },
  { value: 'Warangal' },
  { value: 'Mira-Bhayandar' },
  { value: 'Thiruvananthapuram' },
  { value: 'Bhiwandi' },
  { value: 'Saharanpur' },
  { value: 'Guntur' },
  { value: 'Amravati' },
  { value: 'Bikaner' },
  { value: 'Noida' },
  { value: 'Jamshedpur' },
  { value: 'Bhilai Nagar' },
  { value: 'Cuttack' },
  { value: 'Kochi' },
  { value: 'Udaipur' },
  { value: 'Bhavnagar' },
  { value: 'Dehradun' },
  { value: 'Asansol' },
  { value: 'Nanded-Waghala' },
  { value: 'Ajmer' },
  { value: 'Jamnagar' },
  { value: 'Ujjain' },
  { value: 'Sangli' },
  { value: 'Loni' },
  { value: 'Jhansi' },
  { value: 'Pondicherry' },
  { value: 'Nellore' },
  { value: 'Jammu' },
  { value: 'Belagavi' },
  { value: 'Raurkela' },
  { value: 'Mangaluru' },
  { value: 'Tirunelveli' },
  { value: 'Malegaon' },
  { value: 'Gaya' },
  { value: 'Tiruppur' },
  { value: 'Davanagere' },
  { value: 'Kozhikode' },
  { value: 'Akola' },
  { value: 'Kurnool' },
  { value: 'Bokaro Steel City' },
  { value: 'Rajahmundry' },
  { value: 'Ballari' },
  { value: 'Agartala' },
  { value: 'Bhagalpur' },
  { value: 'Latur' },
  { value: 'Dhule' },
  { value: 'Korba' },
  { value: 'Bhilwara' },
  { value: 'Brahmapur' },
  { value: 'Mysore' },
  { value: 'Muzaffarpur' },
  { value: 'Ahmednagar' },
  { value: 'Kollam' },
  { value: 'Raghunathganj' },
  { value: 'Bilaspur' },
  { value: 'Shahjahanpur' },
  { value: 'Thrissur' },
  { value: 'Alwar' },
  { value: 'Kakinada' },
  { value: 'Nizamabad' },
  { value: 'Sagar' },
  { value: 'Tumkur' },
  { value: 'Hisar' },
  { value: 'Rohtak' },
  { value: 'Panipat' },
  { value: 'Darbhanga' },
  { value: 'Kharagpur' },
  { value: 'Aizawl' },
  { value: 'Ichalkaranji' },
  { value: 'Tirupati' },
  { value: 'Karnal' },
  { value: 'Bathinda' },
  { value: 'Rampur' },
  { value: 'Shivamogga' },
  { value: 'Ratlam' },
  { value: 'Modinagar' },
  { value: 'Durg' },
  { value: 'Shillong' },
  { value: 'Imphal' },
  { value: 'Hapur' },
  { value: 'Ranipet' },
  { value: 'Anantapur' },
  { value: 'Arrah' },
  { value: 'Karimnagar' },
  { value: 'Parbhani' },
  { value: 'Etawah' },
  { value: 'Bharatpur' },
  { value: 'Begusarai' },
  { value: 'New Delhi' },
  { value: 'Chhapra' },
  { value: 'Kadapa' },
  { value: 'Ramagundam' },
  { value: 'Pali' },
  { value: 'Satna' },
  { value: 'Vizianagaram' },
  { value: 'Katihar' },
  { value: 'Hardwar' },
  { value: 'Sonipat' },
  { value: 'Nagercoil' },
  { value: 'Thanjavur' },
  { value: 'Murwara (Katni)' },
  { value: 'Naihati' },
  { value: 'Sambhal' },
  { value: 'Nadiad' },
  { value: 'Yamunanagar' },
  { value: 'English Bazar' },
  { value: 'Eluru' },
  { value: 'Munger' },
  { value: 'Panchkula' },
  { value: 'Raayachuru' },
  { value: 'Panvel' },
  { value: 'Deoghar' },
  { value: 'Ongole' },
  { value: 'Nandyal' },
  { value: 'Morena' },
  { value: 'Bhiwani' },
  { value: 'Porbandar' },
  { value: 'Palakkad' },
  { value: 'Anand' },
  { value: 'Purnia' },
  { value: 'Baharampur' },
  { value: 'Barmer' },
  { value: 'Morvi' },
  { value: 'Orai' },
  { value: 'Bahraich' },
  { value: 'Sikar' },
  { value: 'Vellore' },
  { value: 'Singrauli' },
  { value: 'Khammam' },
  { value: 'Mahesana' },
  { value: 'Silchar' },
  { value: 'Sambalpur' },
  { value: 'Rewa' },
  { value: 'Unnao' },
  { value: 'Hugli-Chinsurah' },
  { value: 'Raiganj' },
  { value: 'Phusro' },
  { value: 'Adityapur' },
  { value: 'Alappuzha' },
  { value: 'Bahadurgarh' },
  { value: 'Machilipatnam' },
  { value: 'Rae Bareli' },
  { value: 'Jalpaiguri' },
  { value: 'Bharuch' },
  { value: 'Pathankot' },
  { value: 'Hoshiarpur' },
  { value: 'Baramula' },
  { value: 'Adoni' },
  { value: 'Jind' },
  { value: 'Tonk' },
  { value: 'Tenali' },
  { value: 'Kancheepuram' },
  { value: 'Vapi' },
  { value: 'Sirsa' },
  { value: 'Navsari' },
  { value: 'Mahbubnagar' },
  { value: 'Puri' },
  { value: 'Robertson Pet' },
  { value: 'Erode' },
  { value: 'Batala' },
  { value: 'Haldwani-cum-Kathgodam' },
  { value: 'Vidisha' },
  { value: 'Saharsa' },
  { value: 'Thanesar' },
  { value: 'Chittoor' },
  { value: 'Veraval' },
  { value: 'Lakhimpur' },
  { value: 'Sitapur' },
  { value: 'Hindupur' },
  { value: 'Santipur' },
  { value: 'Balurghat' },
  { value: 'Ganjbasoda' },
  { value: 'Moga' },
  { value: 'Proddatur' },
  { value: 'Srinagar' },
  { value: 'Medinipur' },
  { value: 'Habra' },
  { value: 'Sasaram' },
  { value: 'Hajipur' },
  { value: 'Bhuj' },
  { value: 'Shivpuri' },
  { value: 'Ranaghat' },
  { value: 'Shimla' },
  { value: 'Tiruvannamalai' },
  { value: 'Kaithal' },
  { value: 'Rajnandgaon' },
  { value: 'Godhra' },
  { value: 'Hazaribag' },
  { value: 'Bhimavaram' },
  { value: 'Mandsaur' },
  { value: 'Dibrugarh' },
  { value: 'Kolar' },
  { value: 'Bankura' },
  { value: 'Mandya' },
  { value: 'Dehri-on-Sone' },
  { value: 'Madanapalle' },
  { value: 'Malerkotla' },
  { value: 'Lalitpur' },
  { value: 'Bettiah' },
  { value: 'Pollachi' },
  { value: 'Khanna' },
  { value: 'Neemuch' },
  { value: 'Palwal' },
  { value: 'Palanpur' },
  { value: 'Guntakal' },
  { value: 'Nabadwip' },
  { value: 'Udupi' },
  { value: 'Jagdalpur' },
  { value: 'Motihari' },
  { value: 'Pilibhit' },
  { value: 'Dimapur' },
  { value: 'Mohali' },
  { value: 'Sadulpur' },
  { value: 'Rajapalayam' },
  { value: 'Dharmavaram' },
  { value: 'Kashipur' },
  { value: 'Sivakasi' },
  { value: 'Darjiling' },
  { value: 'Chikkamagaluru' },
  { value: 'Gudivada' },
  { value: 'Baleshwar Town' },
  { value: 'Mancherial' },
  { value: 'Srikakulam' },
  { value: 'Adilabad' },
  { value: 'Yavatmal' },
  { value: 'Barnala' },
  { value: 'Nagaon' },
  { value: 'Narasaraopet' },
  { value: 'Raigarh' },
  { value: 'Roorkee' },
  { value: 'Valsad' },
  { value: 'Ambikapur' },
  { value: 'Giridih' },
  { value: 'Chandausi' },
  { value: 'Purulia' },
  { value: 'Patan' },
  { value: 'Bagaha' },
  { value: 'Hardoi ' },
  { value: 'Achalpur' },
  { value: 'Osmanabad' },
  { value: 'Deesa' },
  { value: 'Nandurbar' },
  { value: 'Azamgarh' },
  { value: 'Ramgarh' },
  { value: 'Firozpur' },
  { value: 'Baripada Town' },
  { value: 'Karwar' },
  { value: 'Siwan' },
  { value: 'Rajampet' },
  { value: 'Pudukkottai' },
  { value: 'Anantnag' },
  { value: 'Tadpatri' },
  { value: 'Satara' },
  { value: 'Bhadrak' },
  { value: 'Kishanganj' },
  { value: 'Suryapet' },
  { value: 'Wardha' },
  { value: 'Ranebennuru' },
  { value: 'Amreli' },
  { value: 'Neyveli (TS)' },
  { value: 'Jamalpur' },
  { value: 'Marmagao' },
  { value: 'Udgir' },
  { value: 'Tadepalligudem' },
  { value: 'Nagapattinam' },
  { value: 'Buxar' },
  { value: 'Aurangabad' },
  { value: 'Jehanabad' },
  { value: 'Phagwara' },
  { value: 'Khair' },
  { value: 'Sawai Madhopur' },
  { value: 'Kapurthala' },
  { value: 'Chilakaluripet' },
  { value: 'Aurangabad' },
  { value: 'Malappuram' },
  { value: 'Rewari' },
  { value: 'Nagaur' },
  { value: 'Sultanpur' },
  { value: 'Nagda' },
  { value: 'Port Blair' },
  { value: 'Lakhisarai' },
  { value: 'Panaji' },
  { value: 'Tinsukia' },
  { value: 'Itarsi' },
  { value: 'Kohima' },
  { value: 'Balangir' },
  { value: 'Nawada' },
  { value: 'Jharsuguda' },
  { value: 'Jagtial' },
  { value: 'Viluppuram' },
  { value: 'Amalner' },
  { value: 'Zirakpur' },
  { value: 'Tanda' },
  { value: 'Tiruchengode' },
  { value: 'Nagina' },
  { value: 'Yemmiganur' },
  { value: 'Vaniyambadi' },
  { value: 'Sarni' },
  { value: 'Theni Allinagaram' },
  { value: 'Margao' },
  { value: 'Akot' },
  { value: 'Sehore' },
  { value: 'Mhow Cantonment' },
  { value: 'Kot Kapura' },
  { value: 'Makrana' },
  { value: 'Pandharpur' },
  { value: 'Miryalaguda' },
  { value: 'Shamli' },
  { value: 'Seoni' },
  { value: 'Ranibennur' },
  { value: 'Kadiri' },
  { value: 'Shrirampur' },
  { value: 'Rudrapur' },
  { value: 'Parli' },
  { value: 'Najibabad' },
  { value: 'Nirmal' },
  { value: 'Udhagamandalam' },
  { value: 'Shikohabad' },
  { value: 'Jhumri Tilaiya' },
  { value: 'Aruppukkottai' },
  { value: 'Ponnani' },
  { value: 'Jamui' },
  { value: 'Sitamarhi' },
  { value: 'Chirala' },
  { value: 'Anjar' },
  { value: 'Karaikal' },
  { value: 'Hansi' },
  { value: 'Anakapalle' },
  { value: 'Mahasamund' },
  { value: 'Faridkot' },
  { value: 'Saunda' },
  { value: 'Dhoraji' },
  { value: 'Paramakudi' },
  { value: 'Balaghat' },
  { value: 'Sujangarh' },
  { value: 'Khambhat' },
  { value: 'Muktsar' },
  { value: 'Rajpura' },
  { value: 'Kavali' },
  { value: 'Dhamtari' },
  { value: 'Ashok Nagar' },
  { value: 'Sardarshahar' },
  { value: 'Mahuva' },
  { value: 'Bargarh' },
  { value: 'Kamareddy' },
  { value: 'Sahibganj' },
  { value: 'Kothagudem' },
  { value: 'Ramanagaram' },
  { value: 'Gokak' },
  { value: 'Tikamgarh' },
  { value: 'Araria' },
  { value: 'Rishikesh' },
  { value: 'Shahdol' },
  { value: 'Medininagar (Daltonganj)' },
  { value: 'Arakkonam' },
  { value: 'Washim' },
  { value: 'Sangrur' },
  { value: 'Bodhan' },
  { value: 'Fazilka' },
  { value: 'Palacole' },
  { value: 'Keshod' },
  { value: 'Sullurpeta' },
  { value: 'Wadhwan' },
  { value: 'Gurdaspur' },
  { value: 'Vatakara' },
  { value: 'Tura' },
  { value: 'Narnaul' },
  { value: 'Kharar' },
  { value: 'Yadgir' },
  { value: 'Ambejogai' },
  { value: 'Ankleshwar' },
  { value: 'Savarkundla' },
  { value: 'Paradip' },
  { value: 'Virudhachalam' },
  { value: 'Kanhangad' },
  { value: 'Kadi' },
  { value: 'Srivilliputhur' },
  { value: 'Gobindgarh' },
  { value: 'Tindivanam' },
  { value: 'Mansa' },
  { value: 'Taliparamba' },
  { value: 'Manmad' },
  { value: 'Tanuku' },
  { value: 'Rayachoti' },
  { value: 'Virudhunagar' },
  { value: 'Koyilandy' },
  { value: 'Jorhat' },
  { value: 'Karur' },
  { value: 'Valparai' },
  { value: 'Srikalahasti' },
  { value: 'Neyyattinkara' },
  { value: 'Bapatla' },
  { value: 'Fatehabad' },
  { value: 'Malout' },
  { value: 'Sankarankovil' },
  { value: 'Tenkasi' },
  { value: 'Ratnagiri' },
  { value: 'Rabkavi Banhatti' },
  { value: 'Sikandrabad' },
  { value: 'Chaibasa' },
  { value: 'Chirmiri' },
  { value: 'Palwancha' },
  { value: 'Bhawanipatna' },
  { value: 'Kayamkulam' },
  { value: 'Pithampur' },
  { value: 'Nabha' },
  { value: 'Shahabad, Hardoi' },
  { value: 'Dhenkanal' },
  { value: 'Uran Islampur' },
  { value: 'Gopalganj' },
  { value: 'Bongaigaon City' },
  { value: 'Palani' },
  { value: 'Pusad' },
  { value: 'Sopore' },
  { value: 'Pilkhuwa' },
  { value: 'Tarn Taran' },
  { value: 'Renukoot' },
  { value: 'Mandamarri' },
  { value: 'Shahabad' },
  { value: 'Barbil' },
  { value: 'Koratla' },
  { value: 'Madhubani' },
  { value: 'Arambagh' },
  { value: 'Gohana' },
  { value: 'Ladnu' },
  { value: 'Pattukkottai' },
  { value: 'Sirsi' },
  { value: 'Sircilla' },
  { value: 'Tamluk' },
  { value: 'Jagraon' },
  { value: 'AlipurdUrban Agglomerationr' },
  { value: 'Alirajpur' },
  { value: 'Tandur' },
  { value: 'Naidupet' },
  { value: 'Tirupathur' },
  { value: 'Tohana' },
  { value: 'Ratangarh' },
  { value: 'Dhubri' },
  { value: 'Masaurhi' },
  { value: 'Visnagar' },
  { value: 'Vrindavan' },
  { value: 'Nokha' },
  { value: 'Nagari' },
  { value: 'Narwana' },
  { value: 'Ramanathapuram' },
  { value: 'Ujhani' },
  { value: 'Samastipur' },
  { value: 'Laharpur' },
  { value: 'Sangamner' },
  { value: 'Nimbahera' },
  { value: 'Siddipet' },
  { value: 'Suri' },
  { value: 'Diphu' },
  { value: 'Jhargram' },
  { value: 'Shirpur-Warwade' },
  { value: 'Tilhar' },
  { value: 'Sindhnur' },
  { value: 'Udumalaipettai' },
  { value: 'Malkapur' },
  { value: 'Wanaparthy' },
  { value: 'Gudur' },
  { value: 'Kendujhar' },
  { value: 'Mandla' },
  { value: 'Mandi' },
  { value: 'Nedumangad' },
  { value: 'North Lakhimpur' },
  { value: 'Vinukonda' },
  { value: 'Tiptur' },
  { value: 'Gobichettipalayam' },
  { value: 'Sunabeda' },
  { value: 'Wani' },
  { value: 'Upleta' },
  { value: 'Narasapuram' },
  { value: 'Nuzvid' },
  { value: 'Tezpur' },
  { value: 'Una' },
  { value: 'Markapur' },
  { value: 'Sheopur' },
  { value: 'Thiruvarur' },
  { value: 'Sidhpur' },
  { value: 'Sahaswan' },
  { value: 'Suratgarh' },
  { value: 'Shajapur' },
  { value: 'Rayagada' },
  { value: 'Lonavla' },
  { value: 'Ponnur' },
  { value: 'Kagaznagar' },
  { value: 'Gadwal' },
  { value: 'Bhatapara' },
  { value: 'Kandukur' },
  { value: 'Sangareddy' },
  { value: 'Unjha' },
  { value: 'Lunglei' },
  { value: 'Karimganj' },
  { value: 'Kannur' },
  { value: 'Bobbili' },
  { value: 'Mokameh' },
  { value: 'Talegaon Dabhade' },
  { value: 'Anjangaon' },
  { value: 'Mangrol' },
  { value: 'Sunam' },
  { value: 'Gangarampur' },
  { value: 'Thiruvallur' },
  { value: 'Tirur' },
  { value: 'Rath' },
  { value: 'Jatani' },
  { value: 'Viramgam' },
  { value: 'Rajsamand' },
  { value: 'Yanam' },
  { value: 'Kottayam' },
  { value: 'Panruti' },
  { value: 'Dhuri' },
  { value: 'Namakkal' },
  { value: 'Kasaragod' },
  { value: 'Modasa' },
  { value: 'Rayadurg' },
  { value: 'Supaul' },
  { value: 'Kunnamkulam' },
  { value: 'Umred' },
  { value: 'Bellampalle' },
  { value: 'Sibsagar' },
  { value: 'Mandi Dabwali' },
  { value: 'Ottappalam' },
  { value: 'Dumraon' },
  { value: 'Samalkot' },
  { value: 'Jaggaiahpet' },
  { value: 'Goalpara' },
  { value: 'Tuni' },
  { value: 'Lachhmangarh' },
  { value: 'Bhongir' },
  { value: 'Amalapuram' },
  { value: 'Firozpur Cantt.' },
  { value: 'Vikarabad' },
  { value: 'Thiruvalla' },
  { value: 'Sherkot' },
  { value: 'Palghar' },
  { value: 'Shegaon' },
  { value: 'Jangaon' },
  { value: 'Bheemunipatnam' },
  { value: 'Panna' },
  { value: 'Thodupuzha' },
  { value: 'KathUrban Agglomeration' },
  { value: 'Palitana' },
  { value: 'Arwal' },
  { value: 'Venkatagiri' },
  { value: 'Kalpi' },
  { value: 'Rajgarh (Churu)' },
  { value: 'Sattenapalle' },
  { value: 'Arsikere' },
  { value: 'Ozar' },
  { value: 'Thirumangalam' },
  { value: 'Petlad' },
  { value: 'Nasirabad' },
  { value: 'Phaltan' },
  { value: 'Rampurhat' },
  { value: 'Nanjangud' },
  { value: 'Forbesganj' },
  { value: 'Tundla' },
  { value: 'BhabUrban Agglomeration' },
  { value: 'Sagara' },
  { value: 'Pithapuram' },
  { value: 'Sira' },
  { value: 'Bhadrachalam' },
  { value: 'Charkhi Dadri' },
  { value: 'Chatra' },
  { value: 'Palasa Kasibugga' },
  { value: 'Nohar' },
  { value: 'Yevla' },
  { value: 'Sirhind Fatehgarh Sahib' },
  { value: 'Bhainsa' },
  { value: 'Parvathipuram' },
  { value: 'Shahade' },
  { value: 'Chalakudy' },
  { value: 'Narkatiaganj' },
  { value: 'Kapadvanj' },
  { value: 'Macherla' },
  { value: 'Raghogarh-Vijaypur' },
  { value: 'Rupnagar' },
  { value: 'Naugachhia' },
  { value: 'Sendhwa' },
  { value: 'Byasanagar' },
  { value: 'Sandila' },
  { value: 'Gooty' },
  { value: 'Salur' },
  { value: 'Nanpara' },
  { value: 'Sardhana' },
  { value: 'Vita' },
  { value: 'Gumia' },
  { value: 'Puttur' },
  { value: 'Jalandhar Cantt.' },
  { value: 'Nehtaur' },
  { value: 'Changanassery' },
  { value: 'Mandapeta' },
  { value: 'Dumka' },
  { value: 'Seohara' },
  { value: 'Umarkhed' },
  { value: 'Madhupur' },
  { value: 'Vikramasingapuram' },
  { value: 'Punalur' },
  { value: 'Kendrapara' },
  { value: 'Sihor' },
  { value: 'Nellikuppam' },
  { value: 'Samana' },
  { value: 'Warora' },
  { value: 'Nilambur' },
  { value: 'Rasipuram' },
  { value: 'Ramnagar' },
  { value: 'Jammalamadugu' },
  { value: 'Nawanshahr' },
  { value: 'Thoubal' },
  { value: 'Athni' },
  { value: 'Cherthala' },
  { value: 'Sidhi' },
  { value: 'Farooqnagar' },
  { value: 'Peddapuram' },
  { value: 'Chirkunda' },
  { value: 'Pachora' },
  { value: 'Madhepura' },
  { value: 'Pithoragarh' },
  { value: 'Tumsar' },
  { value: 'Phalodi' },
  { value: 'Tiruttani' },
  { value: 'Rampura Phul' },
  { value: 'Perinthalmanna' },
  { value: 'Padrauna' },
  { value: 'Pipariya' },
  { value: 'Dalli-Rajhara' },
  { value: 'Punganur' },
  { value: 'Mattannur' },
  { value: 'Mathura' },
  { value: 'Thakurdwara' },
  { value: 'Nandivaram-Guduvancheri' },
  { value: 'Mulbagal' },
  { value: 'Manjlegaon' },
  { value: 'Wankaner' },
  { value: 'Sillod' },
  { value: 'Nidadavole' },
  { value: 'Surapura' },
  { value: 'Rajagangapur' },
  { value: 'Sheikhpura' },
  { value: 'Parlakhemundi' },
  { value: 'Kalimpong' },
  { value: 'Siruguppa' },
  { value: 'Arvi' },
  { value: 'Limbdi' },
  { value: 'Barpeta' },
  { value: 'Manglaur' },
  { value: 'Repalle' },
  { value: 'Mudhol' },
  { value: 'Shujalpur' },
  { value: 'Mandvi' },
  { value: 'Thangadh' },
  { value: 'Sironj' },
  { value: 'Nandura' },
  { value: 'Shoranur' },
  { value: 'Nathdwara' },
  { value: 'Periyakulam' },
  { value: 'Sultanganj' },
  { value: 'Medak' },
  { value: 'Narayanpet' },
  { value: 'Raxaul Bazar' },
  { value: 'Rajauri' },
  { value: 'Pernampattu' },
  { value: 'Nainital' },
  { value: 'Ramachandrapuram' },
  { value: 'Vaijapur' },
  { value: 'Nangal' },
  { value: 'Sidlaghatta' },
  { value: 'Punch' },
  { value: 'Pandhurna' },
  { value: 'Wadgaon Road' },
  { value: 'Talcher' },
  { value: 'Varkala' },
  { value: 'Pilani' },
  { value: 'Nowgong' },
  { value: 'Naila Janjgir' },
  { value: 'Mapusa' },
  { value: 'Vellakoil' },
  { value: 'Merta City' },
  { value: 'Sivaganga' },
  { value: 'Mandideep' },
  { value: 'Sailu' },
  { value: 'Vyara' },
  { value: 'Kovvur' },
  { value: 'Vadalur' },
  { value: 'Nawabganj' },
  { value: 'Padra' },
  { value: 'Sainthia' },
  { value: 'Siana' },
  { value: 'Shahpur' },
  { value: 'Sojat' },
  { value: 'Noorpur' },
  { value: 'Paravoor' },
  { value: 'Murtijapur' },
  { value: 'Ramnagar' },
  { value: 'Sundargarh' },
  { value: 'Taki' },
  { value: 'Saundatti-Yellamma' },
  { value: 'Pathanamthitta' },
  { value: 'Wadi' },
  { value: 'Rameshwaram' },
  { value: 'Tasgaon' },
  { value: 'Sikandra Rao' },
  { value: 'Sihora' },
  { value: 'Tiruvethipuram' },
  { value: 'Tiruvuru' },
  { value: 'Mehkar' },
  { value: 'Peringathur' },
  { value: 'Perambalur' },
  { value: 'Manvi' },
  { value: 'Zunheboto' },
  { value: 'Mahnar Bazar' },
  { value: 'Attingal' },
  { value: 'Shahbad' },
  { value: 'Puranpur' },
  { value: 'Nelamangala' },
  { value: 'Nakodar' },
  { value: 'Lunawada' },
  { value: 'Murshidabad' },
  { value: 'Mahe' },
  { value: 'Lanka' },
  { value: 'Rudauli' },
  { value: 'Tuensang' },
  { value: 'Lakshmeshwar' },
  { value: 'Zira' },
  { value: 'Yawal' },
  { value: 'Thana Bhawan' },
  { value: 'Ramdurg' },
  { value: 'Pulgaon' },
  { value: 'Sadasivpet' },
  { value: 'Nargund' },
  { value: 'Neem-Ka-Thana' },
  { value: 'Memari' },
  { value: 'Nilanga' },
  { value: 'Naharlagun' },
  { value: 'Pakaur' },
  { value: 'Wai' },
  { value: 'Tarikere' },
  { value: 'Malavalli' },
  { value: 'Raisen' },
  { value: 'Lahar' },
  { value: 'Uravakonda' },
  { value: 'Savanur' },
  { value: 'Sirohi' },
  { value: 'Udhampur' },
  { value: 'Umarga' },
  { value: 'Pratapgarh' },
  { value: 'Lingsugur' },
  { value: 'Usilampatti' },
  { value: 'Palia Kalan' },
  { value: 'Wokha' },
  { value: 'Rajpipla' },
  { value: 'Vijayapura' },
  { value: 'Rawatbhata' },
  { value: 'Sangaria' },
  { value: 'Paithan' },
  { value: 'Rahuri' },
  { value: 'Patti' },
  { value: 'Zaidpur' },
  { value: 'Lalsot' },
  { value: 'Maihar' },
  { value: 'Vedaranyam' },
  { value: 'Nawapur' },
  { value: 'Solan' },
  { value: 'Vapi' },
  { value: 'Sanawad' },
  { value: 'Warisaliganj' },
  { value: 'Revelganj' },
  { value: 'Sabalgarh' },
  { value: 'Tuljapur' },
  { value: 'Simdega' },
  { value: 'Musabani' },
  { value: 'Kodungallur' },
  { value: 'Phulabani' },
  { value: 'Umreth' },
  { value: 'Narsipatnam' },
  { value: 'Nautanwa' },
  { value: 'Rajgir' },
  { value: 'Yellandu' },
  { value: 'Sathyamangalam' },
  { value: 'Pilibanga' },
  { value: 'Morshi' },
  { value: 'Pehowa' },
  { value: 'Sonepur' },
  { value: 'Pappinisseri' },
  { value: 'Zamania' },
  { value: 'Mihijam' },
  { value: 'Purna' },
  { value: 'Puliyankudi' },
  { value: 'Shikarpur, Bulandshahr' },
  { value: 'Umaria' },
  { value: 'Porsa' },
  { value: 'Naugawan Sadat' },
  { value: 'Fatehpur Sikri' },
  { value: 'Manuguru' },
  { value: 'Udaipur' },
  { value: 'Pipar City' },
  { value: 'Pattamundai' },
  { value: 'Nanjikottai' },
  { value: 'Taranagar' },
  { value: 'Yerraguntla' },
  { value: 'Satana' },
  { value: 'Sherghati' },
  { value: 'Sankeshwara' },
  { value: 'Madikeri' },
  { value: 'Thuraiyur' },
  { value: 'Sanand' },
  { value: 'Rajula' },
  { value: 'Kyathampalle' },
  { value: 'Shahabad, Rampur' },
  { value: 'Tilda Newra' },
  { value: 'Narsinghgarh' },
  { value: 'Chittur-Thathamangalam' },
  { value: 'Malaj Khand' },
  { value: 'Sarangpur' },
  { value: 'Robertsganj' },
  { value: 'Sirkali' },
  { value: 'Radhanpur' },
  { value: 'Tiruchendur' },
  { value: 'Utraula' },
  { value: 'Patratu' },
  { value: 'Vijainagar, Ajmer' },
  { value: 'Periyasemur' },
  { value: 'Pathri' },
  { value: 'Sadabad' },
  { value: 'Talikota' },
  { value: 'Sinnar' },
  { value: 'Mungeli' },
  { value: 'Sedam' },
  { value: 'Shikaripur' },
  { value: 'Sumerpur' },
  { value: 'Sattur' },
  { value: 'Sugauli' },
  { value: 'Lumding' },
  { value: 'Vandavasi' },
  { value: 'Titlagarh' },
  { value: 'Uchgaon' },
  { value: 'Mokokchung' },
  { value: 'Paschim Punropara' },
  { value: 'Sagwara' },
  { value: 'Ramganj Mandi' },
  { value: 'Tarakeswar' },
  { value: 'Mahalingapura' },
  { value: 'Dharmanagar' },
  { value: 'Mahemdabad' },
  { value: 'Manendragarh' },
  { value: 'Uran' },
  { value: 'Tharamangalam' },
  { value: 'Tirukkoyilur' },
  { value: 'Pen' },
  { value: 'Makhdumpur' },
  { value: 'Maner' },
  { value: 'Oddanchatram' },
  { value: 'Palladam' },
  { value: 'Mundi' },
  { value: 'Nabarangapur' },
  { value: 'Mudalagi' },
  { value: 'Samalkha' },
  { value: 'Nepanagar' },
  { value: 'Karjat' },
  { value: 'Ranavav' },
  { value: 'Pedana' },
  { value: 'Pinjore' },
  { value: 'Lakheri' },
  { value: 'Pasan' },
  { value: 'Puttur' },
  { value: 'Vadakkuvalliyur' },
  { value: 'Tirukalukundram' },
  { value: 'Mahidpur' },
  { value: 'Mussoorie' },
  { value: 'Muvattupuzha' },
  { value: 'Rasra' },
  { value: 'Udaipurwati' },
  { value: 'Manwath' },
  { value: 'Adoor' },
  { value: 'Uthamapalayam' },
  { value: 'Partur' },
  { value: 'Nahan' },
  { value: 'Ladwa' },
  { value: 'Mankachar' },
  { value: 'Nongstoin' },
  { value: 'Losal' },
  { value: 'Sri Madhopur' },
  { value: 'Ramngarh' },
  { value: 'Mavelikkara' },
  { value: 'Rawatsar' },
  { value: 'Rajakhera' },
  { value: 'Lar' },
  { value: 'Lal Gopalganj Nindaura' },
  { value: 'Muddebihal' },
  { value: 'Sirsaganj' },
  { value: 'Shahpura' },
  { value: 'Surandai' },
  { value: 'Sangole' },
  { value: 'Pavagada' },
  { value: 'Tharad' },
  { value: 'Mansa' },
  { value: 'Umbergaon' },
  { value: 'Mavoor' },
  { value: 'Nalbari' },
  { value: 'Talaja' },
  { value: 'Malur' },
  { value: 'Mangrulpir' },
  { value: 'Soro' },
  { value: 'Shahpura' },
  { value: 'Vadnagar' },
  { value: 'Raisinghnagar' },
  { value: 'Sindhagi' },
  { value: 'Sanduru' },
  { value: 'Sohna' },
  { value: 'Manavadar' },
  { value: 'Pihani' },
  { value: 'Safidon' },
  { value: 'Risod' },
  { value: 'Rosera' },
  { value: 'Sankari' },
  { value: 'Malpura' },
  { value: 'Sonamukhi' },
  { value: 'Shamsabad, Agra' },
  { value: 'Nokha' },
  { value: 'PandUrban Agglomeration' },
  { value: 'Mainaguri' },
  { value: 'Afzalpur' },
  { value: 'Shirur' },
  { value: 'Salaya' },
  { value: 'Shenkottai' },
  { value: 'Pratapgarh' },
  { value: 'Vadipatti' },
  { value: 'Nagarkurnool' },
  { value: 'Savner' },
  { value: 'Sasvad' },
  { value: 'Rudrapur' },
  { value: 'Soron' },
  { value: 'Sholingur' },
  { value: 'Pandharkaoda' },
  { value: 'Perumbavoor' },
  { value: 'Maddur' },
  { value: 'Nadbai' },
  { value: 'Talode' },
  { value: 'Shrigonda' },
  { value: 'Madhugiri' },
  { value: 'Tekkalakote' },
  { value: 'Seoni-Malwa' },
  { value: 'Shirdi' },
  { value: 'SUrban Agglomerationr' },
  { value: 'Terdal' },
  { value: 'Raver' },
  { value: 'Tirupathur' },
  { value: 'Taraori' },
  { value: 'Mukhed' },
  { value: 'Manachanallur' },
  { value: 'Rehli' },
  { value: 'Sanchore' },
  { value: 'Rajura' },
  { value: 'Piro' },
  { value: 'Mudabidri' },
  { value: 'Vadgaon Kasba' },
  { value: 'Nagar' },
  { value: 'Vijapur' },
  { value: 'Viswanatham' },
  { value: 'Polur' },
  { value: 'Panagudi' },
  { value: 'Manawar' },
  { value: 'Tehri' },
  { value: 'Samdhan' },
  { value: 'Pardi' },
  { value: 'Rahatgarh' },
  { value: 'Panagar' },
  { value: 'Uthiramerur' },
  { value: 'Tirora' },
  { value: 'Rangia' },
  { value: 'Sahjanwa' },
  { value: 'Wara Seoni' },
  { value: 'Magadi' },
  { value: 'Rajgarh (Alwar)' },
  { value: 'Rafiganj' },
  { value: 'Tarana' },
  { value: 'Rampur Maniharan' },
  { value: 'Sheoganj' },
  { value: 'Raikot' },
  { value: 'Pauri' },
  { value: 'Sumerpur' },
  { value: 'Navalgund' },
  { value: 'Shahganj' },
  { value: 'Marhaura' },
  { value: 'Tulsipur' },
  { value: 'Sadri' },
  { value: 'Thiruthuraipoondi' },
  { value: 'Shiggaon' },
  { value: 'Pallapatti' },
  { value: 'Mahendragarh' },
  { value: 'Sausar' },
  { value: 'Ponneri' },
  { value: 'Mahad' },
  { value: 'Lohardaga' },
  { value: 'Tirwaganj' },
  { value: 'Margherita' },
  { value: 'Sundarnagar' },
  { value: 'Rajgarh' },
  { value: 'Mangaldoi' },
  { value: 'Renigunta' },
  { value: 'Longowal' },
  { value: 'Ratia' },
  { value: 'Lalgudi' },
  { value: 'Shrirangapattana' },
  { value: 'Niwari' },
  { value: 'Natham' },
  { value: 'Unnamalaikadai' },
  { value: 'PurqUrban Agglomerationzi' },
  { value: 'Shamsabad, Farrukhabad' },
  { value: 'Mirganj' },
  { value: 'Todaraisingh' },
  { value: 'Warhapur' },
  { value: 'Rajam' },
  { value: 'Urmar Tanda' },
  { value: 'Lonar' },
  { value: 'Powayan' },
  { value: 'P.N.Patti' },
  { value: 'Palampur' },
  { value: 'Srisailam Project (Right Flank Colony) Township' },
  { value: 'Sindagi' },
  { value: 'Sandi' },
  { value: 'Vaikom' },
  { value: 'Malda' },
  { value: 'Tharangambadi' },
  { value: 'Sakaleshapura' },
  { value: 'Lalganj' },
  { value: 'Malkangiri' },
  { value: 'Rapar' },
  { value: 'Mauganj' },
  { value: 'Todabhim' },
  { value: 'Srinivaspur' },
  { value: 'Murliganj' },
  { value: 'Reengus' },
  { value: 'Sawantwadi' },
  { value: 'Tittakudi' },
  { value: 'Lilong' },
  { value: 'Rajaldesar' },
  { value: 'Pathardi' },
  { value: 'Achhnera' },
  { value: 'Pacode' },
  { value: 'Naraura' },
  { value: 'Nakur' },
  { value: 'Palai' },
  { value: 'Morinda, India' },
  { value: 'Manasa' },
  { value: 'Nainpur' },
  { value: 'Sahaspur' },
  { value: 'Pauni' },
  { value: 'Prithvipur' },
  { value: 'Ramtek' },
  { value: 'Silapathar' },
  { value: 'Songadh' },
  { value: 'Safipur' },
  { value: 'Sohagpur' },
  { value: 'Mul' },
  { value: 'Sadulshahar' },
  { value: 'Phillaur' },
  { value: 'Sambhar' },
  { value: 'Prantij' },
  { value: 'Nagla' },
  { value: 'Pattran' },
  { value: 'Mount Abu' },
  { value: 'Reoti' },
  { value: 'Tenu dam-cum-Kathhara' },
  { value: 'Panchla' },
  { value: 'Sitarganj' },
  { value: 'Pasighat' },
  { value: 'Motipur' },
  { value: "O' Valley" },
  { value: 'Raghunathpur' },
  { value: 'Suriyampalayam' },
  { value: 'Qadian' },
  { value: 'Rairangpur' },
  { value: 'Silvassa' },
  { value: 'Nowrozabad (Khodargama)' },
  { value: 'Mangrol' },
  { value: 'Soyagaon' },
  { value: 'Sujanpur' },
  { value: 'Manihari' },
  { value: 'Sikanderpur' },
  { value: 'Mangalvedhe' },
  { value: 'Phulera' },
  { value: 'Ron' },
  { value: 'Sholavandan' },
  { value: 'Saidpur' },
  { value: 'Shamgarh' },
  { value: 'Thammampatti' },
  { value: 'Maharajpur' },
  { value: 'Multai' },
  { value: 'Mukerian' },
  { value: 'Sirsi' },
  { value: 'Purwa' },
  { value: 'Sheohar' },
  { value: 'Namagiripettai' },
  { value: 'Parasi' },
  { value: 'Lathi' },
  { value: 'Lalganj' },
  { value: 'Narkhed' },
  { value: 'Mathabhanga' },
  { value: 'Shendurjana' },
  { value: 'Peravurani' },
  { value: 'Mariani' },
  { value: 'Phulpur' },
  { value: 'Rania' },
  { value: 'Pali' },
  { value: 'Pachore' },
  { value: 'Parangipettai' },
  { value: 'Pudupattinam' },
  { value: 'Panniyannur' },
  { value: 'Maharajganj' },
  { value: 'Rau' },
  { value: 'Monoharpur' },
  { value: 'Mandawa' },
  { value: 'Marigaon' },
  { value: 'Pallikonda' },
  { value: 'Pindwara' },
  { value: 'Shishgarh' },
  { value: 'Patur' },
  { value: 'Mayang Imphal' },
  { value: 'Mhowgaon' },
  { value: 'Guruvayoor' },
  { value: 'Mhaswad' },
  { value: 'Sahawar' },
  { value: 'Sivagiri' },
  { value: 'Mundargi' },
  { value: 'Punjaipugalur' },
  { value: 'Kailasahar' },
  { value: 'Samthar' },
  { value: 'Sakti' },
  { value: 'Sadalagi' },
  { value: 'Silao' },
  { value: 'Mandalgarh' },
  { value: 'Loha' },
  { value: 'Pukhrayan' },
  { value: 'Padmanabhapuram' },
  { value: 'Belonia' },
  { value: 'Saiha' },
  { value: 'Srirampore' },
  { value: 'Talwara' },
  { value: 'Puthuppally' },
  { value: 'Khowai' },
  { value: 'Vijaypur' },
  { value: 'Takhatgarh' },
  { value: 'Thirupuvanam' },
  { value: 'Adra' },
  { value: 'Piriyapatna' },
  { value: 'Obra' },
  { value: 'Adalaj' },
  { value: 'Nandgaon' },
  { value: 'Barh' },
  { value: 'Chhapra' },
  { value: 'Panamattom' },
  { value: 'Niwai' },
  { value: 'Bageshwar' },
  { value: 'Tarbha' },
  { value: 'Adyar' },
  { value: 'Narsinghgarh' },
  { value: 'Warud' },
  { value: 'Asarganj' },
  { value: 'Sarsod' },
  { value: 'abohar' }
];

export const productList = [
  {
    name: 'Term Insurance',
    url: require('./../res/images/termins.png'),
  },
  {
    name: 'Health Insurance',
    url: require('./../res/images/healthins.png'),
  },
  {
    name: 'Motor Insurance',
    url: require('./../res/images/motorins.png'),
  },
  {
    name: 'Insurance Samadhan',
    url: require('./../res/images/samadhan.png'),
  },
  {
    name: 'Life Cum Invt. Plan',
    url: require('./../res/images/lifecuminv.png'),
  },
  {
    name: 'Fixed Deposit',
    url: require('./../res/images/fixeddeposit.png'),
  },
  {
    name: 'Mutual Fund',
    url: require('./../res/images/mutualfund.png'),
  },
  {
    name: 'Credit Card',
    url: require('./../res/images/creditcard.png'),
  },
  {
    name: 'Home Loan',
    url: require('./../res/images/homeloan.png'),
  },
  {
    name: 'Loan Against Property',
    url: require('./../res/images/propertyloan.png'),
  },
  {
    name: 'Personal Loan',
    url: require('./../res/images/personalloan.png'),
  },
  {
    name: 'Business Loan',
    url: require('./../res/images/businessloan.png'),
  },
  {
    name: 'Auto Loan',
    url: require('./../res/images/autoloan.png'),
  },
  //   {
  //   name: 'Vector Plus',
  //   url: require('./../res/images/vectorplus.png'),
  // },
  // {
  //   name: 'Insure Check',
  //   url: require('./../res/images/sabseasan.png'),
  // },
  //   {
  //   name: 'Religare Group Plan',
  //   url: require('./../res/images/autoloan.png'),
  // },
  // {
  //   name: 'Hello Doctor Policy',
  //   url: require('./../res/images/erb.png'),
  // },
  // {
  //   name: 'Asaan Health Policy',
  //   url: require('./../res/images/asanhealth.png'),
  // },
  // {
  //   name: 'Sabse Asaan Health Plan',
  //   url: require('./../res/images/sabseasan.png'),
  // },
];

export const productListClone = [
  {
    name: 'Term Insurance',
    url: require('./../res/images/termins.png'),
  },
  {
    name: 'Health Insurance',
    url: require('./../res/images/healthins.png'),
  },
  {
    name: 'Motor Insurance',
    url: require('./../res/images/motorins.png'),
  },
  {
    name: 'Insurance Samadhan',
    url: require('./../res/images/samadhan.png'),
  },
  {
    name: 'Vector Plus',
    url: require('./../res/images/vectorplus.png'),
  },
  {
    name: 'Life Cum Invt. Plan',
    url: require('./../res/images/lifecuminv.png'),
  },
  {
    name: 'Fixed Deposit',
    url: require('./../res/images/fixeddeposit.png'),
  },
  {
    name: 'Mutual Fund',
    url: require('./../res/images/mutualfund.png'),
  },
  {
    name: 'Credit Card',
    url: require('./../res/images/creditcard.png'),
  },
  {
    name: 'Home Loan',
    url: require('./../res/images/homeloan.png'),
  },
  {
    name: 'Loan Against Property',
    url: require('./../res/images/propertyloan.png'),
  },
  {
    name: 'Personal Loan',
    url: require('./../res/images/personalloan.png'),
  },
  {
    name: 'Business Loan',
    url: require('./../res/images/businessloan.png'),
  },
  {
    name: 'Auto Loan',
    url: require('./../res/images/autoloan.png'),
  },
    {
    name: 'Insure Check',
    url: require('./../res/images/sabseasan.png'),
  },
    {
    name: 'Hello Doctor Policy',
    url: require('./../res/images/erb.png'),
  },
  {
    name: 'Asaan Health Policy',
    url: require('./../res/images/asanhealth.png'),
  },
  {
    name: 'Sabse Asaan Health Plan',
    url: require('./../res/images/sabseasan.png'),
  },
];

export const LifeCompany = [{ value: 'Aegon Life Insurance Co. Ltd.' },
{ value: 'Aviva Life Insurance Co. India Ltd.' },
{ value: 'Bajaj Allianz Life Insurance Co. Ltd.' },
{ value: 'Bharti AXA Life Insurance Co. Ltd.' },
{ value: 'Aditya Birla Sun Life Insurance Co. Ltd.' },
{ value: 'Canara HSBC Oriental Bank of Commerce Life Insurance Co. Ltd.' },
{ value: 'DHFL Pramerica Life Insurance Co. Ltd.' },
{ value: 'Edelweiss Tokio Life Insurance Co. Ltd' },
{ value: 'Exide Life Insurance Co. Ltd.' },
{ value: 'Future Generali India Life Insurance Co. Ltd.' },
{ value: 'HDFC Standard Life Insurance Co. Ltd.' },
{ value: 'ICICI Prudential Life Insurance Co. Ltd.' },
{ value: 'IDBI Federal Life Insurance Co. Ltd.' },
{ value: 'IndiaFirst Life Insurance Co. Ltd' },
{ value: 'Kotak Mahindra Old Mutual Life Insurance Ltd.' },
{ value: 'Life Insurance Corporation of India' },
{ value: 'Max Life Insurance Co. Ltd.' },
{ value: 'PNB MetLife India Insurance Co. Ltd.' },
{ value: 'Reliance Life Insurance Co. Ltd.' },
{ value: 'Sahara India Life Insurance Co. Ltd.' },
{ value: 'SBI Life Insurance Co. Ltd.' },
{ value: 'Shriram Life Insurance Co. Ltd.' },
{ value: 'Star Union Dai-Ichi Life Insurance Co. Ltd.' },
{ value: 'Tata AIA Life Insurance Co. Ltd.' },
{ value: 'other' },
{ value: 'None' }]

export const HealthCompany = [{ value: "Acko General Insurance Limited" },
{ value: "Aditya Birla Health Insurance Co. Ltd. " },
{ value: "Agriculture Insurance Co. of India Ltd." },
{ value: "Bajaj Allianz General Insurance Co. Ltd." },
{ value: "Bharti Axa General Insurance Co. Ltd." },
{ value: "Cholamandalam MS General Insurance Co. Ltd." },
{ value: "DHFL General Insurance Co.Ltd." },
{ value: "Edelweiss General Insurance Co.Ltd." },
{ value: "Export Credit Guarantee Corporation of India Ltd." },
{ value: "Future Generali India Insurance Co. Ltd." },
{ value: "Go Digit General Insurance Ltd." },
{ value: "HDFC ERGO General Insurance Co. Ltd." },
{ value: "ICICI Lombard General Insurance Co. Ltd." },
{ value: "IFFCO Tokio General Insurance Co. Ltd." },
{ value: "Kotak Mahindra General Insurance Co. Ltd." },
{ value: "L&amp;T General Insurance Co. Ltd." },
{ value: "Liberty Videocon General Insurance Co. Ltd." },
{ value: "Magma HDI General Insurance Co. Ltd." },
{ value: "Manipal Cigna Health Insurance Co.Ltd." },
{ value: "Max Bupa Health Insurance Co. Ltd." },
{ value: "National Insurance Co. Ltd." },
{ value: "Raheja QBE General Insurance Co. Ltd." },
{ value: "Reliance General Insurance Co. Ltd." },
{ value: "Reliance Health Insurance Limited" },
{ value: "Religare Health Insurance Co. Ltd." },
{ value: "Royal Sundaram Alliance Insurance Co. Ltd." },
{ value: "SBI General Insurance Co. Ltd." },
{ value: "Shriram General Insurance Co. Ltd." },
{ value: "Star Health and Allied Insurance Co. Ltd." },
{ value: "Tata AIG General Insurance Co. Ltd." },
{ value: "The New India Assurance Co. Ltd." },
{ value: "The Oriental Insurance Co. Ltd." },
{ value: "United India Insurance Co. Ltd." },
{ value: "Universal Sompo General Insurance Co. Ltd." },
{ value: "Others" },
{ value: "None" },]

/**
 * Server url
 */
export const profileDefaultPic = `https://cdn.dribbble.com/users/1971922/avatars/normal/f244137353d6ae304c1513dca9ef2a50.jpg`;

export const LiveUrl = `https://erb.ai/erbfinorbit`;
//`http://uat.erb.ai/`; //`https://erb.ai/`;
export const MainUrl = `https://uat.erb.ai/`;
//`https://uat.erb.ai/`;
export const FinURL = `${MainUrl}erbfinorbit/`;
export const BASEUrl = `${MainUrl}corporate_tool/Apis/`;
//export const FOLDERPATH = `${BASEUrl}erbfinorbit`;
export const FinOrbitFormUrl = `${BASEUrl}finorbit/`;

export const DashBoardUrl = `${BASEUrl}tool_dashboard.php`;
export const NewDashBoardUrl = `${BASEUrl}tool_dashboard_api.php`;
export const LoginUrl = `${BASEUrl}tool_login.php`;
export const EmailOTPUrl = `${BASEUrl}tool_email_otp.php`;
export const RegisterUrl = `${BASEUrl}tool_register.php`;
export const GetToken = `${BASEUrl}get_token.php`;
export const AddTeam = `${BASEUrl}tool_add_team.php`;
export const OffersUrl = `${BASEUrl}tool_offers.php`;
export const ViewTeamUrl = `${BASEUrl}tool_view_team.php`;
export const TrainingUrl = `${BASEUrl}tool_training.php`;
export const RelationManagerUrl = `${BASEUrl}tool_managers.php`;
export const BlogsUrl = `${BASEUrl}tool_blogs.php`;
export const WalletInvoiceUrl = `${BASEUrl}tool_get_invoice.php`;
export const ChangePass = `${BASEUrl}tool_change_pass.php`;
export const LeadRecordUrl = `${BASEUrl}tool_lead_record.php`;
export const ViewConnectorUrl = `${BASEUrl}tool_view_connector.php`;
export const WalletUrl = `${BASEUrl}tool_get_wallet.php`;
export const AjaxUrl = `${BASEUrl}tool_ajax.php`;
export const UpdateAccountUrl = `${BASEUrl}tool_update_profile.php`;
export const WalletRedeemUrl = `${BASEUrl}tool_wallet_redeem.php`;
export const ConnectorregisterUrl = `${BASEUrl}tool_connector_register.php`;
export const As26Url = `${BASEUrl}tool_get_26as.php`;
export const CertUrl = `${BASEUrl}tool_cert.php`;
export const PayoutUrl = `${BASEUrl}tool_payout_structure.php`;
export const ConnectorPercentage = `${BASEUrl}tool_payout`;

export const ForgotUrl = `${MainUrl}forgot_all.php`;
export const AgreeUrl = `${MainUrl}corporate_tool/agree.pdf`;
export const TCondition = `${MainUrl}termcondition.php`;
export const TermOfUse = `https://erb.ai/Terms%20of%20Use%20ERB.pdf`;

export const BuyInsurance = `https://forms.gle/LDNnpXDHGwERhhbS9`;

export const AccountViewUrl = `${BASEUrl}tool_view_profile.php`;

export const NewFormPayment = `${FinURL}policy_premium.php`;
export const VectorFormPayment = `${LiveUrl}vp_payment.php`;
export const GroupFormPayment = `${LiveUrl}gp_payment.php`;
export const AjaxWithoutToken = `${FinURL}ajax.php`;
export const NewFormUrl = `${FinURL}aditya_birla_response.php`;
export const FindCityState = `${FinURL}fetchcitystatebypin.php`;

export const PostalCityUrl = `${BASEUrl}tool_view_pincode.php`;

export const VectorFormUrl = `https://www.hpfashion.buzz/erb/app_test.php`;

export const BASEImageUrl = `${BASEUrl}getbase64.php`
//code push
export const PRODUCTION_CODE_PUSH = 'glm7UxfFs5fdrMNn9PQgA84GoR8clOBhLHDqL';
export const STAGING_CODE_PUSH = 'FcVrxLHWW9i6t8Ql9p6uizc_NZwn6Yf8GQ6ig';
//OTP SMS
export const SMS_OTP = `https://api.msg91.com/api/v5/otp`


/**
 * Set Val
 * @param key
 * @param val
 * @returns {Promise<void>}
 */
export const setVal = async (key, val) => {
  let value = JSON.stringify(val);
  if (value) {
    AsyncStorage.setItem(key, value);
  }
};

/**
 * Get value
 * @param key
 * @param callback
 */
export const getVal = (key, callback = (response) => { }) => {
  AsyncStorage.getItem(key).then((value) => {
    callback(JSON.parse(value));
  });
};

/**
 *
 * @param {check number} text
 */
export const returnCheckNumber = (text) => {
  const checkIsNumber = '/[^0-9]/g';
  return checkIsNumber.test(text);
};

export const getFontName = (type) => {
  switch (type) {
    case 1:
      return 'Roboto-Regular';
    case 2:
      return 'Roboto-Light';
    case 3:
      return 'Roboto-Black';
    case 4:
      return 'Roboto-Medium';
    case 5:
      return 'Roboto-Bold';
    case 6:
      return 'Roboto-Thin';
    default:
      return 'Roboto-Regular';
  }
}
