# This is a basic workflow to help you get started with Actions
name: Build Android and iOS

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-adhoc:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3
      - name: Installing node
        uses: actions/setup-node@v1
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Running test
        run: |
          yarn lint
          yarn test


